server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # SỬA LẠI THÀNH 'true' ĐỂ BẬT TÍNH NĂNG GỬI HEADER
        spring.json.add.type.headers: true

        # THÊM DÒNG NÀY ĐỂ GỬI ĐI VỚI "BIỆT DANH"
        spring.json.type.mapping: orderEvent:com.demo.orderservice.dto.OrderEvent


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: false
  packages-to-scan: com.demo.orderservice.controller

logging:
  level:
    com.demo: DEBUG